// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFD7AZ_IRz_XLo5xRZvgdvmnYWqPQnQqc',
    appId: '1:19167663837:android:bf888343c9e17cbabbad34',
    messagingSenderId: '19167663837',
    projectId: 'instantmart-nepal',
    storageBucket: 'instantmart-nepal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdmd56tR5Fj2N7CHKJUgNm-AGtBE49cYA',
    appId: '1:19167663837:ios:ab15b4ba1a58db06bbad34',
    messagingSenderId: '19167663837',
    projectId: 'instantmart-nepal',
    storageBucket: 'instantmart-nepal.firebasestorage.app',
    iosBundleId: 'com.instantmart',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDscWQ0dWdgP7BzkYrwOLjaWWBOs9qS-rA',
    appId: '1:19167663837:web:ac768a896c75701dbbad34',
    messagingSenderId: '19167663837',
    projectId: 'instantmart-nepal',
    authDomain: 'instantmart-nepal.firebaseapp.com',
    storageBucket: 'instantmart-nepal.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc4PQZAYqfrElO9RymZSjFjlAodxyN_ks',
    appId: '1:16246335121:ios:628984907b35cc644bc130',
    messagingSenderId: '16246335121',
    projectId: 'instant-mart-8fb0b',
    storageBucket: 'instant-mart-8fb0b.firebasestorage.app',
    iosBundleId: 'com.instantmart',
  );

}